export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const CAROUSEL_DOWNLOAD_PATH_DATA = 'CAROUSEL_DOWNLOAD_PATH_DATA'

export const UPDATE_LIST = "UPDATE_LIST";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const LOADING = "LOADING";
export const UNLOADING = "UNLOADING";
export const UPDATE_PAGE = "UPDATE_PAGE";